### ISSUE TITLE
Emotion Entries List

### ISSUE THREAD

**Issue by Leon910** [Jennifer-Hinrichsen/emotion-tracker#1]
**As a user**

**I want to** browse a list of emotion entries,

**so that** I can discover and reflect on my emotional states over time.

## Description

![Image](https://github.com/user-attachments/assets/30c0c1b4-d01a-41d9-8f13-1e357d423a75)

## Acceptance Criteria

- The homepage displays a list of emotion entries.
- The emotion entries list is headlined with its purpose.
- Each emotion entry listing includes:
  - Emotion (type)
  - Emotion intensity
  - Date and time
- The entries are ordered chronologically with the newest entries at the top.
- Each emotion type is visually distinct, using different colours or styles to differentiate them.
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [x] Create feature branch `feature/emotion-entries-list`
- [x] Inspect and adapt the example data in the [assets folder](./assets/entries.json)
- [x] Create the component EmotionList, which renders:
- [x] the type of the emotion. [emotion]
- [x] the intensity of the emotion. [intensity]
- [x] the dateTime of the emotion. [dateTime]
- [x] map through the list of Emotions.
- [x] Render the EmotionList component in the index.js. (hint: in this case HomePage)  
- [x] Create a styled Component
