### ISSUE TITLE
Notes length

### ISSUE THREAD

**Issue by Leon910** [Jennifer-Hinrichsen/emotion-tracker#101]
## Value proposition
As a user
I want to see a preview of the notes on the Emotion Card on the homepage,
In order to view the content of my emotions in a reduced format.
## Description
![Image](https://github.com/user-attachments/assets/043fd39c-fbb1-4716-b38b-3342900ba6cd)
![Image](https://github.com/user-attachments/assets/93e47fd2-eb82-4afa-af77-6941f20de783)
## Acceptance criteria
- [ ] The notes are restricted to 50 characters on the Emotion Cards within the Home Page
- [ ] The notes are fully displayed on the Emotion Card within the Details Page
## Tasks
- [ ] Implement logic to restrict the notes to 50 characters on the homepage Emotion Card component
- [ ] Ensure the full note content is displayed on the Emotion Card in the Details Page without truncation
