### ISSUE TITLE
Toastmessages Form completion

### ISSUE THREAD

**Issue by StephieTack** [Jennifer-Hinrichsen/emotion-tracker#16]
## Value proposition

As a user,  
I want immediate and clear feedback when I submit or edit a form,  
so that I can be confident that my changes have been saved successfully.

## Description
![Image](https://github.com/user-attachments/assets/050e586b-51b2-4794-9910-8703232aabd1)
![Image](https://github.com/user-attachments/assets/50438066-b50e-45e0-8a66-c4ef069b4bcb)
![Image](https://github.com/user-attachments/assets/3e1f1fd6-2c7f-4a69-87a0-9d286cb9ea95)

## Acceptance criteria
- [ ] After clicking the "save" button on the editform, the page is closed and the toastmessage is shown on the Detail-page. 
- [ ] After clicking the "submit" button on the HomePage, the same toast message is shown with the difference that it is indicating a successful adding
- [ ] The toast message slides in from the right and gradually becomes more visible until it reaches full color intensity(begins white and went green on the right side).
- [ ] After 3 seconds, the message slides out to the right while gradually fading away.
- [ ] The toast message remains anchored at the bottom-right side until it fades and slides out
- [ ] The toast message is shown several times on one another if the user clicks repeatedly on the submit button.
## Tasks
- [ ] **Create feature branch**` feature/toastmessages`
- [ ] **Set up ToastMessage component**: Create a reusable `ToastMessage` component that displays the toast message. (hint: with props message, visible)
- [ ] **Create ToastMessageContainer**: Implement a ToastMessageContainer component that maps through an array of toast messages and renders the ToastMessage component
- [ ] **Implement ToastMessage Function**: Create a ToastMessage-state and a `showToastMessage`-function inside the _app.js that adds a new toast message to the state 
- [ ] **Integration**: Link the `showToastMessage` to the create and update Emotion handler functions and describe a specific message
- [ ] **Fix Toast Position**: Set the toast message to have a fixed position (bottom-right corner).
- [ ] **Animate Toast Entrance and Exit**: Add functionality for SlideIn and SlideOut with keyframes.
- [ ] **Implement StyledToast**: Style the ToastMessage for the animation (0.3s).

**Comment by F-Kirchhoff** [comment]
Please update your US as follows:
- remove the "strategy" from your value proposition. Toastmessage is one way of fulfilling the need of the user. But what is the need?
- remove placeholder text in decsription.
- remove implementation details like "opacity" from the Acceptance Criteria. you can use something like fading in / fading out.
- Should the toast message be displayed for adding and editing? if so please mention this in the AC.
- Describe where the toast message is fixed.
- The toast message cannot be added to the return statement of the handleSubmit function. Please research how to implement toast messages with a queue and Message Container.

**Comment by JessicaLoers** [comment]
Great work on this.  Writing clear and effective user stories isn’t easy, especially when balancing all the details for a good user experience and technical clarity.  

I’m approving this user story, but I’d love it if you could review my suggestions and keep them in mind for future stories. 


✨ **Here are some hints for further improvement and future User Stories.**

Value proposition

To improve the Value Proposition format, please structure it like this to make it consistent and easy to follow:

```
As a user  `<role>`
I want to   `<action>`
So that I   `<benefit / reason>`
```

Furthermore it could be a bit clearer:

```
As a user,  
I want immediate and clear feedback when I submit or edit a form,  
so that I can be confident that my changes have been saved successfully.
```

**Acceptance criteria**
- In the acceptance criteria, let’s avoid implementation details. These criteria should be written from the **user's perspective**, who wouldn’t know specifics like `edit.js`. 
- Instead, focus on the expected outcome or behavior after the action, rather than how it’s technically achieved. 
- This keeps the criteria user-centered and easier to verify.
