### ISSUE TITLE
Iconset for Emotions

### ISSUE THREAD

**Issue by StephieTack** [Jennifer-Hinrichsen/emotion-tracker#18]
## Value proposition
As a user,
I want to see emotion-icons
so I can quickly identify and differentiate my emotions visually.

## Description
![Image](https://github.com/user-attachments/assets/ae74016f-f585-4098-8249-dd6989241b72)

## Acceptance criteria
- [ ] Each Emotioncard on every page includes an icon on the right corner. 
- [ ] For every existing emotion there is a suitable icon shown on the Emotioncard. 
- [ ] A predefined Iconset must be used by the developer. 

## Tasks
- [x] **Create a feature-branch:** `feature/emotion-icons`.
- [x] **Choose Iconset:**  Choose a set of icons from FontAwesome that match the emotions (e.g., happy, sad, angry, etc.).
- [x] **Install Fontawesome:** `npm install @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome`.
- [ ] **Map icons to emotions**: Create an `emotionIcons` object in a separate file that maps emotion keys (e.g., "happy", "sad") to FontAwesome icons.
- [ ] **Import and configure FontAwesome**: Import FontAwesome in EmotionCard component and the `emotionIcons` mapping.
- [ ] **Render the icons**: Modify the EmotionCard component to render the corresponding icon based on the emotion key in the emotion data.
- [ ] **Adjust styling**: Style the EmotionCard with the new icons regarding the design.

**Comment by JessicaLoers** [comment]
**Good job on the user story!** 

_Of course I have some suggestions. Keep in mind, writing user stories is a skill that we all continue to practice._ 

---

**Value proposition**
The value proposition could be a bit more explicit. Instead of focusing on "appealing visual overview," you could highlight how the icons help users recognise or track their emotions more easily. 

For Example:
**As a user**,
**I want to** see emotion-icons
**so I can** quickly identify and differentiate my emotions visually.

---

**Acceptance criteria**
- The acceptance criteria could be made more specific. For example, it might be useful to define what "appropriate" means in terms of matching icons to emotions. Should there be predefined icons for a fixed set of emotions (e.g., "happy", "sad", "angry"), or should the developer have flexibility? 
- While the tasks include adjusting styling for icons, it might help to include just little bit more design details. For instance, should the icons be displayed in a specific size or color? Should they match the overall theme of the application?
