### ISSUE TITLE
Emotion Entry Details

### ISSUE THREAD

**Issue by Leon910** [Jennifer-Hinrichsen/emotion-tracker#2]
**As a user**

**I want to** access detailed information about each emotion entry,

**so that** I can effectively reflect on my emotional states and understand the context better.

## Description

![Image](https://github.com/user-attachments/assets/a014eb21-d769-4695-8c50-fe5bd042b29e)
## Acceptance Criteria

- Each emotion entry in the emotion entries list has a link to a details page.
- Each details page contains:
  - Emotion (type)
  - Emotion intensity
  - Date and time
  - Notes
- The detailed view includes a “back” link, allowing users to easily navigate back to the list of emotion entries.

## Tasks

- [x] Create feature branch `feature/emotion-entry-details`
- [x] Create the emotions details page pages/emotions/[id].js
- [x] Create the component `EmotionDetails` (edited by Leon - 29.09.)
- [x] Render the EmotionDetails inside [id].js [hint: find and return]
- [x] Read the query parameter id from next/router [hint: [slug].js recap-project-5]
- [x] Add the Link component to navigate back to the homepage [hint: next.js link]
- [x] Add the Link component to navigate to the details page [hint: hover emotion [area]
