### ISSUE TITLE
Statistics 

### ISSUE THREAD

**Issue by StephieTack** [Jennifer-Hinrichsen/emotion-tracker#20]
## Value Proposition
As a user  
I want to view a visual breakdown of my recorded emotions by type and intensity,  
In order to understand patterns in my emotional state over time and identify areas for self-improvement.

## Description
![Image](https://github.com/user-attachments/assets/a8e0b729-173d-4d59-b49e-4783e0ee8678)

## Acceptance Criteria
- [ ] The **Statistics page** is navigable through the navigation bar.
- [ ] The statistics are displayed as **emotion bubbles**, each sized according to the frequency of that emotion.
- [ ] Emotions with the **highest frequency** are displayed at the top, sorted in descending order by frequency.
- [ ] Each bubble reflects the **color** associated with its emotion type.
- [ ] If multiple emotions have the same frequency, they are sorted in descending order by **intensity**.
- [ ] If both frequency and intensity are equal, they are sorted alphabetically by **emotion type**.
- [ ] Next to each bubble, the text "In [Month/Calendar week], you felt **[Emotion]** [X] times, with an average intensity classified as [low/medium/high]." is displayed.
- [ ] The **default view** displays statistics for the current month, with the current month and year **bolded** in the filter options.
- [ ] At least one filter option (month or calendar week) must be selected at all times, and either can be selected.
- [ ] The weekly dropdown shows the **current calendar week and year** in **non-bolded** text.
- [ ] The statistics are **filterable by month or calendar week**, and the filter selection is reflected in the text beside the bubbles.
- [ ] When no emotion can be found for the filtered period of time a message will display the information that there are no matching entries. 

## Tasks
- [x] Create a new **Statistics page component** with routing accessible via the navigation bar.
- [ ] Design and integrate a **bubble chart component** where each bubble visualizes an emotion type:
  - [ ] Set bubble size based on **emotion frequency**.
  - [ ] Color each bubble according to its **emotion type**.
  - [ ] Display the average intensity for each emotion type in the adjacent text.
- [ ] Implement sorting logic to:
  - [ ] Display bubbles in descending order of **frequency**.
  - [ ] Sort bubbles by **intensity** if frequency is the same.
  - [ ] Alphabetically sort by **emotion type** if both frequency and intensity are identical.
- [ ] Develop **filter controls** for switching between weekly and monthly views:
  - [ ] Ensure at least one filter is selected.
  - [ ] Ensure the current month and year is displayed in **bold**.
  - [ ] Ensure the current calendar week and year is displayed in **non-bold** text.
- [ ] Implement logic to dynamically calculate and display the **average intensity** for each bubble's emotion type.
- [ ] Implement condition to check if there are entries. 
- [ ] Fetch emotion data from **local lib files** (e.g., `emotionlist.js`, `initialEmotionEntries.js`).
- [ ] Process the data to calculate **emotion frequency** and **average intensity**.
- [ ] Implement logic to filter the data based on **date ranges** (weekly, monthly) from the local files.

**Comment by F-Kirchhoff** [comment]
Hey Stephie,
your US looks pretty good already, I only have one remark. Your "Backend" is not really a backend, so maybe its no necessary to create subcategories for your tasks.

**Comment by StephieTack** [comment]
Ok! I'll change it :)
