### ISSUE TITLE
Create Emotion Entry

### ISSUE THREAD

**Issue by Leon910** [Jennifer-Hinrichsen/emotion-tracker#3]
**As a user**

**I want to** create and store new emotion entries,

**so that** I can keep track of my emotional states over time.

## Description
![Image](https://github.com/user-attachments/assets/6acd5009-8fdb-4b87-b5cf-d6ce2b6d0034)

## Acceptance Criteria

- A form for adding emotion entries is displayed at the top of the homepage.
- The form is headlined with its purpose.
- The form must include labelled fields for:
  - Emotion (type)
  - Emotion intensity
  - Date and time
  - Notes
- The following fields are mandatory:
  - Emotion (type)
  - Emotion intensity
  - Date and time
- The emotion is selected from the existing emotions list via a dropdown menu.
- The emotion dropdown must include a default option, "Please select an emotion", and necessitates a selection.
- The emotion intensity is selectable on a scale of 1 to 10.
- Date and time is pre-set to the current date and time, but adjustable by the user.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Upon form submission, the new emotion entry is added to the top of the emotion entries list.

## Tasks

- [x] Create feature branch `feature/create-emotion-entry
- [x] Create a EmotionForm-component for adding a new emotion entry
- [x] Add a headline to the form with the title "Add new Emotion"
- [x] Add a labeled dropdown field for "Emotion (type)" and populate it with an emotions list
- [x] Include a default option in the dropdown labeled "Please select an emotion" to enforce selection
- [x] Add a labeled input for "Emotion Intensity" with a scale of 1 to 10
- [x] Add a labeled date and time picker pre-set to the current date and time, but allow user adjustments
- [x] Add a labeled textarea for optional "Notes" input
- [x] Implement client-side validation:
     - [x] Ensure "Emotion (type)", "Emotion Intensity", and "Date and Time" are required fields
     - [x] Define clear error messages for missing required fields
- [x] On form submission, prevent submission if required fields are empty and display validation errors
- [x] After successful form submission, add the new emotion entry to the top of the emotion entries list on the homepage
- [x] Make sure to display notes on the emotion card
- [x] Reset the form to its default state (including resetting the date and time) after submission
- [x] Display a success message after a successful submission or an error message in case of failure
