### ISSUE TITLE
Style Intensity EmotionCard

### ISSUE THREAD

**Issue by StephieTack** [Jennifer-Hinrichsen/emotion-tracker#38]
## Value proposition
As a user,
I want to see a stylish intensity level bar on the Emotion Card
in order to better distinguish between the intensity of my emotions.
## Description
![Image](https://github.com/user-attachments/assets/aece9bda-6e18-495b-8b7a-3918cd03f12b)

## Acceptance criteria
- [ ] The intensity of an emotion is displayed on the **emotion card**.
- [ ] Each **emotion card** shows three bubbles in horizontal line representing intensity levels: low is the left small bubble, medium is the bubble in the middle with a medium size, and high is the right big bubble.
- [ ] All bubbles are displayed in the color associated with the emotion type, with opacity adjustments based on selected intensity level.
 - [ ] **Low** displays only the first intensity bubble at full color opacity (and the other two with reduced background color opacity).
  - [ ] **Medium** displays the first two intensity bubbles at full color opacity (and the right biggest one with reduced background color opacity).
  - [ ] **High** displays all three intensity bubbles at full color opacity.

## Tasks
- [ ] Implement intensity bubbles directly in the `EmotionCardContent` component.
- [ ] Map over the intensity values (1, 2, 3) in `EmotionCardContent` to display bubbles with different sizes.
- [ ] Set the size of the bubbles dynamically based on the intensity level (e.g., 10px, 20px, 30px for low, mid, and high).
- [ ] Use the `background-color` property with conditional logic to apply color and adjust the background color's opacity based on the selected intensity level.
- [ ] Pass the `intensity` value from the `emotion` object directly to `EmotionCardContent` and map it to bubble size.
- [ ] Ensure the bubbles' background color matches the associated emotion color, based on `emotion.type.color`.
- [ ] Update the rendering logic for intensity in `EmotionCardContent` to reflect the correct bubble display based on the `intensity` value.

**Comment by F-Kirchhoff** [comment]
Hey,
I am a bit confused by your intensity levels, do you have a range from 1-10 or three levels low mid and high? And how should be bubble size change according to the intensity level? Are you displaying 3 levels as well as resize all 3 bubbles depending on a second intensity value?
