### ISSUE TITLE
Assign Colors to Emotions

### ISSUE THREAD

**Issue by Jennifer-Hinrichsen** [Jennifer-Hinrichsen/emotion-tracker#40]
## Value proposition
As a user
I want to see each user card to be highlighted with a distinct color
In order to easily distinguish between different emotions.
## Description
![Image](https://github.com/user-attachments/assets/f6d05148-5fac-4074-bfc8-9508dcffe5a5)
## Acceptance criteria
- [ ] The color of the date and time frame should match the pre-defined UX/UI color for each emotion.
- [ ] The color should be visible on the Emotion Card in all of the existing pages.
## Tasks
- [x] **Create a new branch** `feature/connect-emotion-with-color`
- [ ] **Store** predefined colors in a configuration file (e.g. `utils/colorUtils.js`) where each emotion type (e.g., happy, sad, excited) has a corresponding color code
- [ ] **Create** a function to retrieve/map the correct color for each emotion type from the predefined palette
- [ ] **Modify** the ColorCard-component to accept a color prop
- [ ] **Style** the Color Card based on the received color, ensuring each card reflects the assigned color
