### ISSUE TITLE
Cancel Button EditForm

### ISSUE THREAD

**Issue by Leon910** [Jennifer-Hinrichsen/emotion-tracker#43]
## Value proposition
As a user,
I want to be able to cancel my changes while editing an emotion entry on the Detail page,
So that I can exit the editing mode without saving unwanted modifications.

## Description

- Add a "Cancel" button to the Edit Form that is left to the save button.
- When clicked, the Cancel button should close the form and discard any unsaved changes.

## Acceptance criteria
- [ ] A Cancel button is visible on the Edit Form on the Detail page.
- [ ] After clicking Cancel, the view should return to the Emotion Details view.

## Tasks
- [ ] Create a new branch: `feature/add-cancel-button-edit-form`.
- [ ] Add a Cancel button to the Edit Form on the Detail page.
- [ ] Implement functionality to close the Edit Form and discard changes when Cancel is clicked.
- [ ] Test: Ensure clicking Cancel reverts to the Emotion Details view without saving changes.

**Comment by levinthiel** [comment]
Hi @W-Schkulov, 
- Consider adding a wireframe to better situate the cancel button within the form.

- Wouldn't it be more prudent to ask, "are you sure you want to cancel ? " before cancelling the form ?

**Comment by W-Schkulov** [comment]
> Hi [@W-Schkulov](https://github.com/W-Schkulov),
> 
> * Consider adding a wireframe to better situate the cancel button within the form.
> * Wouldn't it be more prudent to ask, "are you sure you want to cancel ? " before cancelling the form ?

Thanks for the feedback! For this particular feature, we believe a wireframe isn’t necessary, given the straightforward nature of adding a Cancel button. However, we appreciate the suggestion!
