### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by Jennifer-Hinrichsen** [Jennifer-Hinrichsen/emotion-tracker#45]
## Value proposition
As a user
I want to see a favicon next to the URL
In order to have a direct visual feedback on what website I am currently on
## Description
- The favicon should clearly represent the brand of the app.
- It should be simple, recognizable, and optimized for various device and screen sizes.
## Acceptance criteria
- [ ] The Favicon is displayed in the browser next to the URL 
- [ ] The Favicon is displayed on every single dynamic routing page
- [ ] The favicon is visible in bookmarks when the page is saved.
## Tasks
- [ ] Create a branch `feature/favicon`
- [ ] Design a favicon that represents the website or brand.
- [ ] Export the favicon in required formats and sizes (e.g., `.ico` and `.png`).
- [ ] Add the favicon to the project with proper HTML link tags for various devices and browsers.
