### ISSUE TITLE
AI Driven Feedback

### ISSUE THREAD

**Issue by StephieTack** [Jennifer-Hinrichsen/emotion-tracker#46]
## Value Proposition  
**As a user**
**I want to** receive AI-driven feedback on my entered Emotion
**so that** I get relevant feedback on the EmotionCardDetailPage with additional context to my feeling.

## Description  
![Image](https://github.com/user-attachments/assets/c4d4a6ec-1452-4a77-96c6-ad9fe60d9c1f)
![Image](https://github.com/user-attachments/assets/8b87ef2c-3825-4e76-9c3b-cb1821aefe0e)

## Acceptance Criteria  
- [ ] The AI generated feedbacksection is displayed at the end of the emotionCard on the Detail Page.  
- [ ] The feedback is displayed only after the user clicks a button i.e. "Show feedback" at the end of the emotionCard to toggle its visibility.  
- [ ] The length of the feedback is maximum 3 sentences. 
- [ ] If the feedback is currently visible and the user clicks the button "Hide feedback" again, the feedback is hidden.  
- [ ] The feedback is dynamically generated using the entered emotion, intensity, and optional notes.  
- [ ] If the "notes" field contains input, a relation to it is included in the feedback generation.  

## Tasks  
**Create Branch**
   - [ ] Create feature branch `feature/ai-driven-feedback`

**Backend Integration with OpenAI API**
   - [ ] import OpenAI from "openai";
   - [ ] Integrate the OpenAI API key into the backend (e.g., in a `.env` file).
   - [ ] Create an API route that forwards the requests to OpenAI. /api/feedback/generate.js
   - [ ] Ensure the API endpoint processes emotion types, intensity and notes from the frontend.
   - [ ] Set:  const prompt = `Provide actionable and empathetic feedback for an emotion entry. 
  The emotion type is '${emotionType}' with an intensity level ${intensity} of 3. 
  The user has notes: '${notes ? notes : "No notes provided"}'. 
  Offer practical advice or support tailored to the situation.`;
   - [ ] Make a request using the openai package.
   - [ ] Find the relevant data in the response and send it back to the client. 

 **Frontend Integration**
Fetch Emotion Entry Data:  
   - [ ] Use the `emotionId` from the URL to fetch the emotion entry data (e.g., type, intensity, and notes).  
   - [ ] Use `useSWR` to load data dynamically.  
   
Request Feedback Generation:  
   - [ ] Send a request to `/api/feedback/generate` with the `emotionType`, `intensity`, and `notes` as parameters.  
   
Update FE with Feedback:  
   - [ ] Display a toggleButton to show or hide the feedback.

**Comment by F-Kirchhoff** [comment]
There are a couple of problems with your US:
- please provide a wireframe of the feature UI
- in the AC, describe the exact workflow for a user and how the feedback is generated. 
- Clear concise functionality is not an AC, this cannot be tested. You can remove it.
-  ??????useEffect??! does not look professional, please remove this and overthing if you really need a useEffect (you don't ;) ). You need either useSWR or fetch.

**Comment by StephieTack** [comment]
@F-Kirchhoff  Thank you for your feedback. I've revised the story.
