### ISSUE TITLE
Update Emotion Entry

### ISSUE THREAD

**Issue by Leon910** [Jennifer-Hinrichsen/emotion-tracker#5]
## Value Proposition

**As a user**

**I want to** update the details of existing emotion entries,

**so that** they reflect the most accurate and relevant information.

## Description

![3FAB875D-2540-44CF-A24C-DEACC543CF67](https://github.com/user-attachments/assets/d81eef80-70e7-4d57-bd62-c426b7c5b841)

## Acceptance Criteria

- Each emotion entry details page includes an easily accessible edit option.
- Clicking the edit option opens a new page with a form pre-filled with the emotion entry’s existing details for modification.
- The form allows for edits to all emotion entry details, including:
  - Emotion (type)
  - Emotion intensity
  - Date and time
  - Notes
- The following fields are mandatory:
  - Emotion (type)
  - Emotion intensity
  - Date and time
- The form section includes options for both saving and cancelling the action.
- The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- Submissions with empty required fields are blocked, with validation messages indicating the missing required fields.
- Upon confirming the save, the user is immediately redirected to the details page of the edited emotion entry, and the changes are saved and reflected.

## Tasks

- [x] Create feature branch `feature/update-emotion-entry`
- [x] Implement an edit-button inside the EmotionDetails-component
- [x] Create a new page /pages/emotions/[id]/edit.js
- [x] onEdit use the existing EmotionForm-component which handles the update of the existing emotion and show it on page "edit.js"
- [x] Prop-handling for the Headline of the form and for the "save"-button
- [x] Implement a handleUpdate-function with useState
- [x] Implement a router.push method to redirect to the EmotionDetails-page

**Comment by F-Kirchhoff** [comment]
the second to last task looks more like an Acceptance Criteria (please keep in mind that you only have one usestate at that time, that for the entire entries list).
