### ISSUE TITLE
Opener with animation

### ISSUE THREAD

**Issue by Jennifer-Hinrichsen** [Jennifer-Hinrichsen/emotion-tracker#53]
## Value proposition
As a user
I want an app opener with an engaging animation
so that the app provides an inviting and dynamic first impression.
## Description
![Image](https://github.com/user-attachments/assets/21122393-fa94-4485-a81d-d81f5f3e264c)

## Acceptance criteria
- [ ] The animation should only be displayed the first time the user visits the homepage; subsequent visits should bypass the animation.
- [ ] During this animation, only the animation itself is visible.
## Tasks
- [ ] Create a feature branch: `feature/opener-animation`
