### ISSUE TITLE
Replace Icons

### ISSUE THREAD

**Issue by Jennifer-Hinrichsen** [Jennifer-Hinrichsen/emotion-tracker#62]
## Value proposition
As a user,
I want to see icons that match the overall design,
in order to experience a more visually cohesive and pleasant interface.
## Description
![Image](https://github.com/user-attachments/assets/bce7b677-855a-4feb-afc5-ce0cd9e54ee5)
![Image](https://github.com/user-attachments/assets/70ae50bd-c479-4efd-a5ca-69c3c3377e5e)

## Acceptance criteria
- [ ] All icons are updated to match the new design style.
- [ ] Icons are consistent across all components and pages.
## Tasks
- [ ] **Create a new branch**: Name: feature/replace-iconset
- [ ] **Update icon references** across all components with the new icon set.
