### ISSUE TITLE
Calendar Popup

### ISSUE THREAD

**Issue by Leon910** [Jennifer-Hinrichsen/emotion-tracker#68]
## Value proposition
As a user,
I want to quickly access the create emotion form via a button in the popup window,
so that I can create a new emotion without navigating through multiple steps.
## Description
![Image](https://github.com/user-attachments/assets/d6e7294d-b9d9-4a0d-81ed-151f55a449ad)
![Image](https://github.com/user-attachments/assets/17d0bd3e-494e-4d0d-885c-22be253d6a5a)
## Acceptance criteria
- [x] The popup window displays the date as a headline.
- [x] The popup window displays a message when no emotions are available for the selected day.
- [x] A "Create one" button is displayed on the bottom of the popup window no matter if there are emotions or not.
- [x] Clicking the "Create Emotion" button directs the user to the Emotion Form of the Home Page.
- [x] The Emotion Form extends automatically.
- [ ] The date and time of the Emotion Form is preselected with the day the user selected from the calendar
- [x] An "X" button is displayed in the top-right corner of the popup window.
- [x] Clicking the "X" button closes the popup window.
## Tasks
- [ ] Create a new branch: `feature/calendar-popup`.
- [ ] Display the selected date as a headline in the popup window.
- [ ] Conditional render a message when no emotions exist for the selected day.
- [ ] Add a "Create one" button/Link with functionality to redirect to the Emotion Form.
- [ ] Ensure the Emotion Form is automatically expanded upon redirection.
- [ ] Pre-fill the date and time fields in the Emotion Form with the selected date.
- [ ] Include an "X" button to close the popup.
- [ ] Implement functionality to close the popup window when the "X" button is clicked.
