### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by Leon910** [Jennifer-Hinrichsen/emotion-tracker#72]
## Value proposition
As a user,
I want to see a footer with a about link,
so that I can easily find and access additional information about the creators of the application.
## Description
![Image](https://github.com/user-attachments/assets/d99b15b6-c8b4-4b94-9d2e-0a1f5260f438)
## Acceptance criteria
- [x] The footer is consistently visible at the bottom of the home page, regardless of the content length.
- [x] The footer includes an about link.
- [x] The link directs to a dedicated information page.
- [x] The design of the footer should be consistent with the overall website styling.
## Tasks
- [x] Design the footer component  with an next.js-LINK.
- [x] Create an about  page as a dynamic page.
- [x] Ensure the footer is visible only on the home page, regardless of the content.
