### ISSUE TITLE
Backend update/delete

### ISSUE THREAD

**Issue by Leon910** [Jennifer-Hinrichsen/emotion-tracker#74]
## Value proposition
As a user,
I want to be able to update and delete my emotions,
so that I can keep my emotion records accurate and remove entries that are no longer relevant.
## Acceptance criteria
- [ ] The application ensures that the emotions are updated.
- [ ] Deleted emotions are no longer stored in the database.
## Tasks
- [x] Create a new branch: feature/backend-update-delete
- [x] Define a PUT API route and connect the submit handler of an edit form to this API route
- [x] Define a DELETE API route and
connect a handler function which uses this API route
- [x] Add handler functions in both a general and a dynamic route with the methods PUT and DELETE
