### ISSUE TITLE
Fixing Toastmessage

### ISSUE THREAD

**Issue by Jennifer-Hinrichsen** [Jennifer-Hinrichsen/emotion-tracker#80]
## Value proposition
As a user,
I want the toast message to reappear when I press the submit button,
in order to receive immediate feedback on my action.
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] After clicking the "save" button on the Edit-Form, the page is closed and the toast message is shown on the Details-page.
- [ ] After clicking the "submit" button on the HomePage, the same toast message is shown with the difference that it is indicating a successful adding
- [ ] The toast message slides in from the right and gradually becomes more visible until it reaches full color intensity(begins white and went green on the right side).
- [ ] After 3 seconds, the message slides out to the right while gradually fading away.
- [ ] The toast message remains anchored at the bottom-right side until it fades and slides out
- [ ] The toast message is shown several times on one another if the user clicks repeatedly on the submit button
## Tasks
- [ ] Create a new branch: feature/fix-toastmessage.
