### ISSUE TITLE
Developer Story: Fixed Styling

### ISSUE THREAD

**Issue by Jennifer-Hinrichsen** [Jennifer-Hinrichsen/emotion-tracker#89]
## Value proposition
As a user,
I want the styling of the website to be fixed,
In order to find it more visually appealing, engaging, and easier to use.
## Description
The website's styling should be adjusted consistently across all sections. Aria Labels should be added.
## Acceptance criteria
- [ ] In dark mode, the eyes of the icons should be dark.
- [ ] In dark mode, the text on the buttons should be dark.
- [ ] The headline "Create Emotion Type" should only display as "Create"
- [ ] In dark mode, the search icon should appear in a lighter color.
- [ ] Adding aria-labels for better Accessibility.
- [ ] Optimize the padding and margin of the search bar.
- [ ] Fixing the styling of the Submit Button on all forms.
## Tasks
- [ ] List the tasks that need to be performed within the dev team
