### ISSUE TITLE
Optimize Buttons

### ISSUE THREAD

**Issue by StephieTack** [Jennifer-Hinrichsen/emotion-tracker#93]
## Value proposition
As a user,
I want to optimize the buttons with icons, adjust their colors, sizes, and positions,
In order to improve the UI consistency and user experience.

## Description
- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria
- [ ] The Buttons in the options Menu and on the DetailsPage should show icons.
- [ ]  The color should match the theme. 
- [ ] Button sizes should be consistent across the UI.
## Tasks
- [ ] List the tasks that need to be performed within the dev team
